FE : 퀴즈 등록 페이지
Team-MorJo/MorJo pull request #19
Opened 2024-11-21 11:21 UTC by sybang97

## 기능
- 퀴즈 등록 페이지
  - isLoggedIn을 이용한 내비게이션 가드 설정 및 비로그인 시 문제 등록 불가
  - 정답 선택 기능
  - 문제 내용, 선택지, 정답 중 하나라도 비어있으면 퀴즈 등록 불가
  - 문제 내용 및 선택지 글자 수 혹은 Byte 제한
  - 선택지 2개에서 4개까지 줄이고 늘이기 가능

2024-11-21 17:56 UTC, puranium235 requested changes
고생하셨습니다! 몇가지 코드 스타일만 조금 고치면 좋을거같아용
그리고 몇가지 버그도 발견했는데
- 문제 내용에 개행이 들어가고 우리가 테스트한 크기보다 훨씬 크게까지 만들어짐
- 한번이라도 문제를 두줄 이상 입력했으면 내용을 다 지워도 박스 크기가 두줄임
- 문제와 선지가 길어지면 맨 아래 경고문구가 바닥에 붙게되어 아래 여백 필요
감사합니다! 내일도 화이팅!

2024-11-21 17:56 UTC, puranium235 commented on backend/src/main/java/com/morjo/model/service/UserService.java
> +        System.out.println(user);
되도록이면 `fe`브랜치에서 백엔드 코드는 건드리지 않는게 좋아
`commit` 할때 `git status`로 백엔드 코드가 올라가는지 한번 확인해보고 하거나 `VSCode`의 깃 익스텐션을 이용하면 좋다!

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/api/quizApi.js
> +    })
JavaScript에서 객체를 생성할 때 `Shorthand property names`라고 key를 따로 넣지 않으면 변수 이름이 그대로 들어가! 그리고 매개변수를 받을 때도 6개를 이렇게 받으면 순서를 헷갈리거나 의도하지 않은 값을 넣을 수 있어서 좋지 않아

처음부터 이렇게 객체로 받으면 간편하긴 하지만 객체에 어떤 값이 들어가야하는지 알 수 없고, 이상한 객체가 매개변수로 들어와도 거를 수 없기때문에 좋은 방법은 아니라고 생각해
```
export const postQuizCreate = async (quiz) => {
  try {
    const response = await api.post('/quiz/create', quiz)
```

그래서 이렇게 구조분해할당된 객체를 매개변수로 받으면 순서에 상관없이 해당되는 key의 값만 받을 수 있어
```suggestion
export const postQuizCreate 
    = async ({ content, option1, option2, option3, option4, answer }) => {
  try {
    const response = await api.post('/quiz/create', {
      content,
      option1,
      option2,
      option3,
      option4,
      answer,
    })
```
참고
[MDN Object Initializer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) 
[Airbnb Style Guide](https://github.com/airbnb/javascript?tab=readme-ov-file#destructuring)

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/components/common/TheHeader.vue
> +      <span @click="goToQuizRegister" class="create">문제등록 | </span>
- 이벤트 핸들러 함수는 관례적으로 `handle`로 시작해
- `Register`와 `Create`를 혼용하면 오해의 여지가 있으니까 통일해서 사용하면 좋을것같아

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/components/common/TheHeader.vue
> +.login, .logout, .create {
`cursor` 말고는 바뀌는게 없으니까 클래스를 세개 만들 필요 없이 `pointer`같은 클래스를 주는게 더 좋을거같아

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +    <!-- 문제 내용 입력 컴포넌트 -->
좋은 코드는 주석 없이도 이해되는 코드라고 보통 해
아주 복잡한 알고리즘이 아닌 이상 주석이 아니라 변수명, 함수명, 컴포넌트명으로 의미를 전달하려고 시도해봐

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizSolveView.vue
> +  min-width: 450px;
굳 감사합니다

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/components/quiz/QuizCreateOption.vue
> +const props = defineProps({
`script`태그 내에서 사용하지 않을거라면(`template`에서만 사용한다면) 변수에 할당할 필요 없어

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +        <label :for="'option' + index" class="answer-button" :class="{ 'selected': answer === index + 1 }">
- `JavaScript`의 `Template literals` 기능을 사용하면 `+`연산자 없이 문자열 내에 변수를 넣을 수 있어
이렇게 하는게 더 직관적으로 이해하기 편하고, 작성하기도 편해
- 동적 바인딩을 사용하지 않을거라면 앞에 `:`를 붙이지 않고 쓸 수 있어

```suggestion
        <input type="radio" name="option" :value="index + 1" v-model="answer" :id="`option${index}`" hidden />
        <label :for="`option${index}`" class="answer-button" :class="{ 'selected': answer === index + 1 }">
```

참고
[MDN Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +    <i v-if="options.length < 4" class="bi bi-plus-lg add-button" @click="addOption"></i>
`i` 태그는 `italic`의 약자로 주로 외국어나 용어 등을 강조할 때 사용해
여기서 특별히 이걸 사용한 이유가 없으면 `button`태그를 사용하는게 더 의미상 맞을거같아
```suggestion
    <button v-if="options.length < 4" class="bi bi-plus-lg add-button" @click="addOption"></button>
```
참고
[MDN Element <i>](https://developer.mozilla.org/ko/docs/Web/HTML/Element/i)

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +          @input="handleOptionInput(index, $event)" />
- 컴포넌트를 in-Dom 템플릿에서 `kebab-case`로 사용하는 경우 셀프 클로징 컴포넌트로 사용하면 안돼
참고
[Vue Style Guide 우선순위 B](https://ko.vuejs.org/style-guide/rules-strongly-recommended.html#self-closing-components)
```suggestion
        <quiz-create-option :value="option" :placeholder="`선택지 ${index + 1} 을 입력하세요`"
          @input="handleOptionInput(index, $event)" ></quiz-create-option>
```

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +          <i :class="answer === index + 1 ? 'bi bi-check-square' : 'bi bi-square'"></i>
이거 `label` 태그에 class 넣어서 바로 하는건 안되나?

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +const errorMessage = ref("")
전체적으로 `errorMessage`를 수동으로 관리하고 있는데, `watch`를 이용해서 한번에 처리할수도 있지 않을까?

2024-11-21 17:56 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
전체적으로 파일이 좀 큰거같긴 하네..
`QuizCreateOption`이 입력칸만 있는거같은데 체크박스와 `-`표시까지 포함하면 더 깔끔하게 보일 것 같아

2024-11-22 02:12 UTC, sybang97 commented on backend/src/main/java/com/morjo/model/service/UserService.java
> +        System.out.println(user);
명심하겠습니다!

2024-11-22 02:34 UTC, sybang97 commented on frontend/src/api/quizApi.js
> +    })
적용했습니다.

2024-11-22 03:49 UTC, sybang97 commented on frontend/src/components/common/TheHeader.vue
> +      <span @click="goToQuizRegister" class="create">문제등록 | </span>
정정했습니다.

2024-11-22 03:52 UTC, sybang97 commented on frontend/src/components/common/TheHeader.vue
> +.login, .logout, .create {
수정했습니다.

2024-11-22 03:54 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +    <!-- 문제 내용 입력 컴포넌트 -->
주석 제거했습니다.

2024-11-22 04:07 UTC, sybang97 commented on frontend/src/components/quiz/QuizCreateOption.vue
> +const props = defineProps({
정정했습니다.

2024-11-22 04:17 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +        <label :for="'option' + index" class="answer-button" :class="{ 'selected': answer === index + 1 }">
적용했습니다.

2024-11-22 04:35 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +    <i v-if="options.length < 4" class="bi bi-plus-lg add-button" @click="addOption"></i>
bootstrap icon을 사용하여 icon의 의미로 `i` 태그를 사용했습니다.

2024-11-22 04:38 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +          @input="handleOptionInput(index, $event)" />
정정했습니다.

2024-11-22 04:39 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +          <i :class="answer === index + 1 ? 'bi bi-check-square' : 'bi bi-square'"></i>
bootstrap icon에서 `i` 태그 사용을 권장하고 있습니다.

2024-11-22 04:40 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
> +const errorMessage = ref("")
시간이 나면 처리해보겠습니다.
일단 보류

2024-11-22 04:55 UTC, sybang97 commented on frontend/src/views/QuizCreateView.vue
이 또한 보류하고 시간이 나면 처리해보겠습니다. 고생하셨어용

2024-11-22 05:02 UTC, sybang97 commented
> 고생하셨습니다! 몇가지 코드 스타일만 조금 고치면 좋을거같아용 그리고 몇가지 버그도 발견했는데
> 
> * 문제 내용에 개행이 들어가고 우리가 테스트한 크기보다 훨씬 크게까지 만들어짐
> * 한번이라도 문제를 두줄 이상 입력했으면 내용을 다 지워도 박스 크기가 두줄임
> * 문제와 선지가 길어지면 맨 아래 경고문구가 바닥에 붙게되어 아래 여백 필요
>   감사합니다! 내일도 화이팅!

- 개행문제는 `input`으로 작성하면 해결이 가능하지만 `autoResize`가 작동하지 않는 것을 확인했습니다. 다른 해결 방법을 찾아보겠습니다.
- 박스 크기는 한 글자라도 작성을 하면 두 줄이 되는 것을 확인했습니다. 해결 방법을 찾아보겠습니다.
- 경고 문구가 바닥에 붙는 문제는 `padding` 혹은 `margin`으로 처리하여 해결하겠습니다.
- 하경이도 화이팅~!

2024-11-22 11:03 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +        <quiz-create-option :value="option" :placeholder="'선택지 ' + (index + 1) + '을 입력하세요'"
`placeholder`의 문구도 `template literal`로 써주세요

2024-11-22 11:04 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +  <div v-if="errorMessage" class="alert">
`errorMessage`가 자주 생겼다 없어졌다 하니까 `v-show`로 하는게 더 맞을거같아

2024-11-22 11:05 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +    console.log(data)
디버깅용 콘솔은 지워주세요

2024-11-22 11:06 UTC, puranium235 commented on frontend/src/views/QuizCreateView.vue
> +import { getSpecificQuiz, postQuizCreate } from "@/api/quizApi";
사용하지 않는 `import`는 정리해주세요

2024-11-22 11:20 UTC, puranium235 approved these changes
고생하셨습니다

2024-11-22 11:20 UTC, merged