FE: 퀴즈 결과 제출
Team-MorJo/MorJo pull request #24
Opened 2024-11-23 16:26 UTC by sybang97

- 퀴즈 결과 제출 기능 추가

2024-11-23 16:28 UTC, sybang97 commented
BE 작업 후에 develop으로 브랜치를 안바꾸고 새브랜치를 만들어서 했더니 이전 커밋 기록까지 추가되어있네요..?
다음부턴 주의하겠습니다.

2024-11-24 04:42 UTC, puranium235 commented
> BE 작업 후에 develop으로 브랜치를 안바꾸고 새브랜치를 만들어서 했더니 이전 커밋 기록까지 추가되어있네요..? 다음부턴 주의하겠습니다.

이렇게 하면 `be` 브랜치를 기반으로 새 브랜치가 파져서 그렇습니다 괜찮아요~

2024-11-24 05:31 UTC, puranium235 requested changes
좋아용~

2024-11-24 05:31 UTC, puranium235 commented on frontend/src/api/quizApi.js
> +}
`api` 함수는 지난번처럼 구조분해할당된 형태로 받아서 다시 조립하는게 좋을것같아

2024-11-24 05:31 UTC, puranium235 commented on frontend/src/views/QuizSolveView.vue
>    }
변수의 scope는 작을수록 좋아서 `submit` 함수 안에서만 사용하는 변수는 `submit`함수 안에 선언하는게 더 좋아!
`quizSubmit`이라는 변수를 `template`안에서 반응형으로 사용하는건 아니니까 굳이 반응형으로 만들 필요도 없어. 이렇게 해주면 될듯?
```JavaScript
const quizSbumit = {
  quizId,
  userAnswer,
  isCommonSense,
}
```

2024-11-24 08:52 UTC, sybang97 commented on frontend/src/api/quizApi.js
> +}
적용했습니다~

2024-11-24 08:55 UTC, sybang97 commented on frontend/src/views/QuizSolveView.vue
>    }
`quizId`, `userAnswer`, `isCommonSense`는 반응형 변수로 되어있어서, shorthand property는 적용 못하고 `quizSubmit`은 `submit` 함수 안에 선언 했습니다~

2024-11-24 11:22 UTC, puranium235 approved these changes, later dismissed

2024-11-24 11:39 UTC, puranium235 submitted a review, later dismissed

2024-11-25 02:10 UTC, puranium235 requested changes
고생하셨습니다

2024-11-25 02:10 UTC, puranium235 commented on frontend/src/views/QuizSolveView.vue
>    }
여기가 원래 `home`이 아니면 (== `quiz`면) 다음문제가 안나오게 하는 로직이라 지워버리면 될 것 같습니다

2024-11-25 02:31 UTC, puranium235 approved these changes
굳 고생하셨습니다

2024-11-25 02:31 UTC, merged